#########################################################################
# Dependabot configuration file
#########################################################################

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00" # UTC
    open-pull-requests-limit: 20
    commit-message:
      prefix: "Upgrade: [dependabot] - "

  ###################################
  # NPM     #########################
  ###################################
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00" # UTC
    open-pull-requests-limit: 20
    commit-message:
      prefix: "Upgrade: [dependabot] - "
    versioning-strategy: increase

  ###################################
  # Poetry  #########################
  ###################################
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00" # UTC
    open-pull-requests-limit: 20
    commit-message:
      prefix: "Upgrade: [dependabot] - "
    versioning-strategy: increase
