name: "setup_workspace"
description: "Setup workspace and install dependencies"

inputs:
  BRANCH_NAME:
    description: "Branch name to checkout"
    required: true
    default: "main"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.BRANCH_NAME }}
        fetch-depth: 0

    # using git commit sha for version of action to ensure we have stable version
    - name: Install asdf
      uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6
      with:
        asdf_branch: v0.11.3

    - name: Cache asdf
      uses: actions/cache@v3
      with:
        path: |
          ~/.asdf
        key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
        restore-keys: |
          ${{ runner.os }}-asdf-

    - name: Install asdf dependencies in .tool-versions
      uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6
      with:
        asdf_branch: v0.11.3
      env:
        PYTHON_CONFIGURE_OPTS: --enable-shared

    - name: make install
      run: |
        make install
