name: quality checks

on:
  workflow_call:
    inputs:
      BRANCH_NAME:
        type: string
        required: true
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  quality_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup workspace
        uses: ./.github/actions/setup_workspace
        with:
          BRANCH_NAME: ${{ github.event.inputs.BRANCH_NAME }}

      - name: run check-licenses
        run: make check-licenses

      - name: run lint
        run: make lint

      - name: run build
        run: make build

      - name: run unit tests
        run: make test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
