name: quality checks

on:
  workflow_call:
    inputs:
      BRANCH_NAME:
        type: string
        required: true
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  quality_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.BRANCH_NAME }}
          fetch-depth: 0

      - name: Setup workspace
        uses: ./.github/actions/setup_workspace

      - name: run check-licenses
        run: make check-licenses

      - name: run lint
        run: make lint

      - name: Build
        uses: ./.github/actions/build

      - name: Test
        uses: ./.github/actions/test
