name: Dependabot Prefix PR Title

on:
  workflow_call:
permissions:
  pull-requests: write

jobs:
  prefix-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from Dependabot
        run: |
          if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
            echo "PR is from Dependabot."
            echo "PR_IS_DEPENDABOT=true" >> $GITHUB_ENV
          else
            echo "PR is not from Dependabot."
            echo "No change to PR title."
            echo "PR_IS_DEPENDABOT=false" >> $GITHUB_ENV
          fi

      - name: Check if PR title is already prefixed
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ ^Chore:.*[dependabot].*-.*$ ]]; then
            echo "PR title is already prefixed."
            echo "No change to PR title."
            echo "PR_IS_PREFIXED=true" >> $GITHUB_ENV
          else
            echo "PR title is not prefixed."
            echo "PR_IS_PREFIXED=false" >> $GITHUB_ENV
          fi

      - name: Update PR title with Prefix
        if: ${{ env.PR_IS_DEPENDABOT == 'true' }} && ${{ env.PR_IS_PREFIXED == 'false' }}
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const new_title = `Chore: [dependabot] - ${{ github.event.pull_request.title }}`
            console.log(`Updating PR title to: ${new_title}`)

            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              title: new_title
            })
